version: "3.8"
services:
  rust-services:
    build: ./rust-services
    container_name: rust-services
    ports:
      - "4000:4000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
    networks:
      - app-network

  nest-services:
    build: ./nest-services
    container_name: nest-services
    ports:
      - "3000:3000"
    environment:
      - RUST_API_URL=${RUST_API_URL}
      - NEST_API_PORT=${NEST_API_PORT}
    depends_on:
      rust-services:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
