   [phases.setup]
   nixPkgs = ["rustc", "cargo", "pkg-config", "openssl"]
   rustVersion = "latest"

   [phases.build]
   cmds = [
     "cd rust-services && rm Cargo.lock",  # ลบ Cargo.lock เก่า
     "cd rust-services && cargo build --release"  # สร้าง Cargo.lock ใหม่
   ]

   [start]
   cmd = "cd rust-services && ./target/release/rust-services"